name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint_and_push:
    name: Linting and Push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Find run_linting.bat
        run: |
          linting_script=$(find . -name "run_linting.bat" -type f | head -n 1)
          echo "Found linting script at: $linting_script"
          chmod +x "$linting_script"

      - name: Run linting
        run: $linting_script
        continue-on-error: true

      - name: Push code if linting passed
        if: ${{ success() }}
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Linting issues fixed"
          git push origin main
