name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Code Linting and Formatting
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install flake8 and black
        run: |
          pip install flake8 black

      - name: Run linting and formatting
        run: |
          flake8 .
          black --check .

  push_to_main:
    name: Push to main if linting issues are fixed
    runs-on: ubuntu-latest
    needs: lint
    if: ${{ needs.lint.result == 'success' }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Push changes to main branch
        run: |
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"
          git push origin main
